### ISSUE TITLE
Issue javascript

### ISSUE THREAD

**Issue by Kerem-Tutucu** [Recss68/fix-the-flow-interactive-website#1]
https://github.com/Recss68/fix-the-flow-interactive-website/blob/33bcb2974a2bb6b60af23b889008f035fc433a8a/opdracht%202/index.js#L4-L14

Dit gedeelte is niet handig om in je javascript bestand te zetten. Dit komt omdat oude telefoons javascript niet kunnen inladen/uit hebben staan. Zet het daarom voor de volgende keer in je style.css.

**Comment by Recss68** [comment]
e60250bb2e795430e6e4a7bf9abc2f9abe05735c

**Comment by Recss68** [comment]
e60250bb2e795430e6e4a7bf9abc2f9abe05735c
