### ISSUE TITLE
issue javascript aangemaakte variabelen

### ISSUE THREAD

**Issue by Kerem-Tutucu** [Recss68/fix-the-flow-interactive-website#2]
De aangemaakte variabelen zijn soms wat onduidelijk. 
https://github.com/Recss68/fix-the-flow-interactive-website/blob/33bcb2974a2bb6b60af23b889008f035fc433a8a/opdracht%202/index.js#L5
Welk tekstbedoel je hiermee? is het de hele tekst of een kopje? Dat kan wat duidelijker voor de volgende keer.

**Comment by Recss68** [comment]
c1b5ee921c86b0ab52103e4d1a306aece898f05a
