### ISSUE TITLE
feedforward

### ISSUE THREAD

**Issue by Anouarab2** [Recss68/fix-the-flow-interactive-website#4]
feedforward is alleen de knop zelf maar, het is niet heel duidlelijk wat er gaat gebeuren, zet bijvoorbeeld een pijltje om te laten zien dat er tekst onder komt

**Comment by Anouarab2** [comment]
@KyanTG @misspastelwitch

**Comment by Recss68** [comment]
591e4a213d326a4ff9c20f298ace067341a418fd
