### ISSUE TITLE
Probeer dit met minder code op te lossen

### ISSUE THREAD

**Issue by KrijnHoetmer** [Recss68/fix-the-flow-interactive-website#6]
Hierdoor wordt het straks makkelijker om snelle code te schrijven. Zoek dus uit hoe je met classList.toggle() en slimme(re) CSS dit probleem kunt oplossen.

https://github.com/Recss68/fix-the-flow-interactive-website/blob/76193580f98cd521ea5fa880021fd1da260bdbb8/opdracht%202/index.js#L7-L17

**Comment by Recss68** [comment]
132c6e2b4c6a7713ce9d9a6e50b5990559a47db6

**Comment by KrijnHoetmer** [comment]
Nice!

Nog een pro-tip: je kunt je commit messages koppelen aan issue, door in je commit message het nummer van je issue te noemen (“code korter gemaakt (#6)” in dit geval). Je hoeft dan niet handmatig de commit te noemen. En je kunt het issue [zelfs automatisch laten sluiten](https://github.blog/news-insights/product-news/closing-issues-via-commit-messages/) met een commit (“code korter gemaakt (fixes #6)” in dit geval) — waarschijnlijk wil je in de toekomst ook al je commit messages in het Engels gaan maken, maar dat komt nog wel.
