### ISSUE TITLE
Feedback/Feedforward

### ISSUE THREAD

**Issue by KrijnHoetmer** [Recss68/fix-the-flow-interactive-website#7]
Zorg dat je 'Zie meer' bijvoorbeeld naar 'Zie minder' gaat, dus laat de UI ook de nieuwe feedforward tonen.

Kijk ook even naar de workshop van maandag, over schetsen: https://github.com/fdnd-task/fix-the-flow-interactive-website/blob/main/docs/user-interface-design.md

**Comment by Recss68** [comment]
ce128ad608286b2893ba34a2326834ef37789933

**Comment by KrijnHoetmer** [comment]
Beter!

Als je 'm helemaal af wilt maken, zorg dan dat die teksten niet in JS staan, maar in je HTML (net als dat je styling niet in JS zet, zet je content het liefst niet in JS). Die 'Zie meer' staat er al, maar je zou bijvoorbeeld via een [`data` attribuut](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) op je button het andere tekstje ook in de HTML kunnen zetten. Via de `dataset` property kun je die dan in JS aanspreken. Dan heb je de teksten op één plek staan, en kun je je script makkelijker op meerdere plekken inzetten.
